import * as m from "@/paraglide/messages.js";
// Demo conversation data for pre-populated scenarios
export const DEMO_CONVERSATIONS = {
  "ai-comparison": {
    title: m.copy_ai_model_comparison_demo(),
    description: m.copy_see_how_different_ai_models_approach_the_same_question(),
    messages: [
      {
        id: "demo-1",
        role: "user" as const,
        content: m.copy_what_s_the_most_exciting_technology_trend_in_2025(),
        xPosition: 100,
        yPosition: 100,
        nodeType: "conversation" as const,
        isCollapsed: false,
      },
      {
        id: "demo-2",
        role: "assistant" as const,
        content: m.copy_ai_agents_are_transforming_how_we_work_and_interact_with_technol(),
        model: "openai/gpt-5-mini",
        parentId: "demo-1",
        xPosition: 300,
        yPosition: 50,
        nodeType: "conversation" as const,
        isCollapsed: false,
      },
      {
        id: "demo-3",
        role: "assistant" as const,
        content: m.copy_quantum_computing_is_reaching_practical_applications_in_2025_wit(),
        model: "anthropic/claude-3-sonnet",
        parentId: "demo-1",
        branchName: m.copy_claudes_perspective(),
        xPosition: 300,
        yPosition: 150,
        nodeType: "branching_point" as const,
        isCollapsed: false,
      },
    ],
  },
  "creative-writing": {
    title: m.copy_creative_writing_exploration(),
    description: m.copy_explore_different_narrative_styles_and_creative_approaches(),
    messages: [
      {
        id: "demo-4",
        role: "user" as const,
        content: m.copy_help_me_write_a_short_story_about_a_robot_discovering_emotions(),
        xPosition: 100,
        yPosition: 100,
        nodeType: "conversation" as const,
        isCollapsed: false,
      },
      {
        id: "demo-5",
        role: "assistant" as const,
        content: m.copy_the_first_tear_unit_47_stood_in_the_abandoned_library_its_optica(),
        model: "openai/gpt-5-mini",
        parentId: "demo-4",
        branchName: m.copy_emotional_narrative(),
        xPosition: 350,
        yPosition: 50,
        nodeType: "conversation" as const,
        isCollapsed: false,
      },
      {
        id: "demo-6",
        role: "user" as const,
        content: m.copy_that_s_beautiful_can_you_explore_what_happens_next(),
        parentId: "demo-5",
        xPosition: 600,
        yPosition: 50,
        nodeType: "conversation" as const,
        isCollapsed: false,
      },
    ],
  },
  "problem-solving": {
    title: m.copy_complex_problem_solving(),
    description: m.copy_break_down_complex_problems_using_multiple_ai_perspectives(),
    messages: [
      {
        id: "demo-7",
        role: "user" as const,
        content: m.copy_how_can_cities_reduce_traffic_congestion_while_improving_air_qua(),
        xPosition: 100,
        yPosition: 100,
        nodeType: "conversation" as const,
        isCollapsed: false,
      },
      {
        id: "demo-8",
        role: "assistant" as const,
        content: m.copy_smart_infrastructure_approach_1_dynamic_traffic_management_ai_po(),
        model: "anthropic/claude-3-sonnet",
        parentId: "demo-7",
        branchName: m.copy_infrastructure_focus(),
        xPosition: 350,
        yPosition: 50,
        nodeType: "insight" as const,
        isCollapsed: false,
      },
      {
        id: "demo-9",
        role: "assistant" as const,
        content: m.copy_sustainable_transportation_revolution_micro_mobility_e_scooters(),
        model: "meta/llama-3.1-70b-instruct",
        parentId: "demo-7",
        branchName: m.copy_sustainability_focus(),
        xPosition: 350,
        yPosition: 200,
        nodeType: "insight" as const,
        isCollapsed: false,
      },
    ],
  },
} as const;
