import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardContent } from "@/components/ui/card";
import Link from "@/lib/navigation";
import {
  FileText,
  Users,
  Shield,
  AlertTriangle,
  Gavel,
  Bot,
  Key,
  Ban,
  RefreshCw,
} from "lucide-react";
import InfoSection from "@/components/info-section";
import { sx } from "@/styles/sx";

export default function TermsOfUse() {
  return (
    <main {...sx("flex-auto px-4 py-12 sm:px-6 lg:px-8")}>
      <div {...sx("mx-auto max-w-5xl mt-6")}>
        <Button
          render={<Link href="/" />}
          nativeButton={false}
          variant="ghost"
          className="mb-8 text-primary hover:text-primary/80 transition-colors"
        >
          <span {...sx("mr-2")} aria-hidden="true">
            &larr;
          </span>{" "}
          Back to home
        </Button>

        <Card className="overflow-hidden shadow-lg border-none">
          <CardHeader className="bg-primary text-neutral-50">
            <h1 {...sx("text-3xl font-bold tracking-tight sm:text-4xl")}>Terms of Use</h1>
          </CardHeader>
          <CardContent className="p-6 sm:p-10">
            <div {...sx("mb-8 text-sm text-muted-foreground")}>
              <p>Last updated: April 2026</p>
            </div>

            <div {...sx("prose prose-neutral max-w-none mb-8")}>
              <p {...sx("text-lg text-muted-foreground")}>
                Welcome to Zermind! These Terms of Use govern your access to and use of our AI chat
                application. By using Zermind, you agree to these terms.
              </p>
            </div>

            <div {...sx("grid gap-6 sm:grid-cols-1 lg:grid-cols-2")}>
              <InfoSection
                icon={FileText}
                title="Service Description"
                content={[
                  "Zermind is an open-source AI chat and mind-map application",
                  "Provides access to multiple LLM providers through Convex Agent workflows",
                  "Enables synchronized chat history, branching, and mind-map metadata",
                  "Supports real-time streaming responses and collaborative sessions",
                  "Supports file attachments through Convex file storage",
                ]}
              />

              <InfoSection
                icon={Users}
                title="User Accounts"
                content={[
                  "You must provide accurate account information",
                  "You are responsible for account security",
                  "One account per person or organization",
                  "Must be 13 years or older to use the service",
                  "Accounts may be suspended for violations",
                ]}
              />

              <InfoSection
                icon={Bot}
                title="AI Service Usage"
                content={[
                  "AI responses are generated by third-party providers",
                  "We do not guarantee accuracy of AI responses",
                  "You are responsible for verifying AI-generated content",
                  "Responses may vary between different AI models",
                  "Service availability depends on third-party APIs",
                ]}
              />

              <InfoSection
                icon={Key}
                title="API Keys & BYOK"
                content={[
                  "You may provide your own API keys (BYOK)",
                  "You are responsible for the accuracy, permissions, billing, and security of your keys",
                  "Usage costs with your keys are your responsibility",
                  "We are not liable for unauthorized API key usage outside our reasonable control",
                  "API keys are encrypted before storage and are never returned to clients",
                ]}
              />

              <InfoSection
                icon={Ban}
                title="Prohibited Uses"
                content={[
                  "Illegal activities or unlawful content generation",
                  "Harassment, hate speech, abuse, or harmful content",
                  "Uploading malicious files or content that infringes others' rights",
                  "Spamming, scraping, credential abuse, or automated misuse",
                  "Attempting to bypass security controls or disrupt the service",
                  "Violating third-party AI provider terms",
                ]}
              />

              <InfoSection
                icon={Shield}
                title="Content & Privacy"
                content={[
                  "You retain ownership of your prompts, chats, uploads, and generated content where legally permitted",
                  "You grant us the limited rights needed to operate, store, transmit, and display your content",
                  "Shared chats become publicly accessible to anyone with the share link",
                  "We do not train AI models on your data",
                  "Your data is processed according to our Privacy Policy",
                  "You can delete your content from the app, subject to provider and backup retention limits",
                ]}
              />

              <InfoSection
                icon={AlertTriangle}
                title="Disclaimers"
                content={[
                  "Service provided 'as is' without warranties",
                  "No guarantee of uninterrupted availability or permanent storage",
                  "AI responses may contain inaccuracies, unsafe suggestions, or biases",
                  "Third-party service dependencies, including Convex, Vercel, and AI providers, may affect functionality",
                  "Uploaded files and AI outputs should be reviewed before relying on them",
                  "Open source nature means community contributions may evolve the service",
                ]}
              />

              <InfoSection
                icon={Gavel}
                title="Limitation of Liability"
                content={[
                  "Our liability is limited to the maximum extent permitted by law",
                  "Not liable for indirect or consequential damages",
                  "No liability for third-party AI provider actions",
                  "Your use of AI responses is at your own risk",
                  "Total liability limited to service fees paid (if any)",
                ]}
              />

              <InfoSection
                icon={RefreshCw}
                title="Service Changes"
                content={[
                  "We may modify, limit, or discontinue features",
                  "Terms may be updated with notice where required",
                  "New features, providers, collaboration tools, or storage features may have additional terms",
                  "Open source nature allows community forks subject to the project license",
                  "Breaking changes will be communicated when reasonably possible",
                ]}
              />
            </div>

            <div {...sx("mt-8 border-t pt-6 text-sm text-muted-foreground space-y-4")}>
              <div>
                <h2 {...sx("font-semibold text-primary mb-2")}>Open Source License</h2>
                <p>
                  Zermind is licensed under the MIT License. The source code is available on{" "}
                  <a
                    href="https://github.com/okikeSolutions/zermind"
                    {...sx("text-primary hover:text-primary/80 transition-colors")}
                  >
                    GitHub
                  </a>
                  . You may fork, modify, and distribute the code under the license terms.
                </p>
              </div>

              <div>
                <h2 {...sx("font-semibold text-primary mb-2")}>Third-Party Services</h2>
                <p>
                  Zermind integrates with services including Convex, Vercel, Better Auth,
                  OpenRouter, and AI providers such as OpenAI, Anthropic, Google, Meta-compatible
                  models, and others. Your use of these integrations is subject to their respective
                  terms of service.
                </p>
              </div>

              <div>
                <h2 {...sx("font-semibold text-primary mb-2")}>Governing Law</h2>
                <p>
                  These terms are governed by Austrian law. Disputes will be resolved in Austrian
                  courts. For consumer disputes, you may also use the EU Online Dispute Resolution
                  platform.
                </p>
              </div>

              <div>
                <h2 {...sx("font-semibold text-primary mb-2")}>Contact Information</h2>
                <p>
                  For questions about these terms, contact us at{" "}
                  <a
                    href="mailto:info@okike-solutions.com"
                    {...sx("text-primary hover:text-primary/80 transition-colors")}
                  >
                    info@okike-solutions.com
                  </a>
                  . See our{" "}
                  <Link
                    href="/imprint"
                    {...sx("text-primary hover:text-primary/80 transition-colors")}
                  >
                    Imprint
                  </Link>{" "}
                  for full contact details.
                </p>
              </div>

              <div>
                <h2 {...sx("font-semibold text-primary mb-2")}>Severability</h2>
                <p>
                  If any provision of these terms is found unenforceable, the remaining provisions
                  will continue in full force and effect.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
