/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DemoRouteImport } from "./routes/demo";
import { Route as ImprintRouteImport } from "./routes/imprint";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as ProtectedRouteImport } from "./routes/protected";
import { Route as ShareRouteImport } from "./routes/share";
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as AuthErrorRouteImport } from "./routes/auth.error";
import { Route as AuthForgotPasswordRouteImport } from "./routes/auth.forgot-password";
import { Route as AuthLoginRouteImport } from "./routes/auth.login";
import { Route as AuthSignUpRouteImport } from "./routes/auth.sign-up";
import { Route as AuthSignUpSuccessRouteImport } from "./routes/auth.sign-up-success";
import { Route as AuthUpdatePasswordRouteImport } from "./routes/auth.update-password";
import { Route as CollaborateChatIdRouteImport } from "./routes/collaborate.$chatId";
import { Route as DemoIndexRouteImport } from "./routes/demo.index";
import { Route as DemoScenarioRouteImport } from "./routes/demo.$scenario";
import { Route as ProtectedIndexRouteImport } from "./routes/protected.index";
import { Route as ProtectedSettingsRouteImport } from "./routes/protected.settings";
import { Route as ProtectedUsageRouteImport } from "./routes/protected.usage";
import { Route as ShareShareIdRouteImport } from "./routes/share.$shareId";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as ProtectedChatIdRouteImport } from "./routes/protected.chat.$id";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoRoute = DemoRouteImport.update({
  id: "/demo",
  path: "/demo",
  getParentRoute: () => rootRouteImport,
} as any);
const ImprintRoute = ImprintRouteImport.update({
  id: "/imprint",
  path: "/imprint",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: "/protected",
  path: "/protected",
  getParentRoute: () => rootRouteImport,
} as any);
const ShareRoute = ShareRouteImport.update({
  id: "/share",
  path: "/share",
  getParentRoute: () => rootRouteImport,
} as any);
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: "/auth/error",
  path: "/auth/error",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/auth/forgot-password",
  path: "/auth/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: "/auth/sign-up",
  path: "/auth/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignUpSuccessRoute = AuthSignUpSuccessRouteImport.update({
  id: "/auth/sign-up-success",
  path: "/auth/sign-up-success",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: "/auth/update-password",
  path: "/auth/update-password",
  getParentRoute: () => rootRouteImport,
} as any);
const CollaborateChatIdRoute = CollaborateChatIdRouteImport.update({
  id: "/collaborate/$chatId",
  path: "/collaborate/$chatId",
  getParentRoute: () => rootRouteImport,
} as any);
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DemoRoute,
} as any);
const DemoScenarioRoute = DemoScenarioRouteImport.update({
  id: "/$scenario",
  path: "/$scenario",
  getParentRoute: () => DemoRoute,
} as any);
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedUsageRoute = ProtectedUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => ProtectedRoute,
} as any);
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: "/$shareId",
  path: "/$shareId",
  getParentRoute: () => ShareRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedChatIdRoute = ProtectedChatIdRouteImport.update({
  id: "/chat/$id",
  path: "/chat/$id",
  getParentRoute: () => ProtectedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/demo": typeof DemoRouteWithChildren;
  "/imprint": typeof ImprintRoute;
  "/privacy": typeof PrivacyRoute;
  "/protected": typeof ProtectedRouteWithChildren;
  "/share": typeof ShareRouteWithChildren;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms": typeof TermsRoute;
  "/auth/error": typeof AuthErrorRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/auth/sign-up-success": typeof AuthSignUpSuccessRoute;
  "/auth/update-password": typeof AuthUpdatePasswordRoute;
  "/collaborate/$chatId": typeof CollaborateChatIdRoute;
  "/demo/$scenario": typeof DemoScenarioRoute;
  "/protected/settings": typeof ProtectedSettingsRoute;
  "/protected/usage": typeof ProtectedUsageRoute;
  "/share/$shareId": typeof ShareShareIdRoute;
  "/demo/": typeof DemoIndexRoute;
  "/protected/": typeof ProtectedIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/protected/chat/$id": typeof ProtectedChatIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/imprint": typeof ImprintRoute;
  "/privacy": typeof PrivacyRoute;
  "/share": typeof ShareRouteWithChildren;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms": typeof TermsRoute;
  "/auth/error": typeof AuthErrorRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/auth/sign-up-success": typeof AuthSignUpSuccessRoute;
  "/auth/update-password": typeof AuthUpdatePasswordRoute;
  "/collaborate/$chatId": typeof CollaborateChatIdRoute;
  "/demo/$scenario": typeof DemoScenarioRoute;
  "/protected/settings": typeof ProtectedSettingsRoute;
  "/protected/usage": typeof ProtectedUsageRoute;
  "/share/$shareId": typeof ShareShareIdRoute;
  "/demo": typeof DemoIndexRoute;
  "/protected": typeof ProtectedIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/protected/chat/$id": typeof ProtectedChatIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/demo": typeof DemoRouteWithChildren;
  "/imprint": typeof ImprintRoute;
  "/privacy": typeof PrivacyRoute;
  "/protected": typeof ProtectedRouteWithChildren;
  "/share": typeof ShareRouteWithChildren;
  "/sitemap.xml": typeof SitemapDotxmlRoute;
  "/terms": typeof TermsRoute;
  "/auth/error": typeof AuthErrorRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/auth/sign-up-success": typeof AuthSignUpSuccessRoute;
  "/auth/update-password": typeof AuthUpdatePasswordRoute;
  "/collaborate/$chatId": typeof CollaborateChatIdRoute;
  "/demo/$scenario": typeof DemoScenarioRoute;
  "/protected/settings": typeof ProtectedSettingsRoute;
  "/protected/usage": typeof ProtectedUsageRoute;
  "/share/$shareId": typeof ShareShareIdRoute;
  "/demo/": typeof DemoIndexRoute;
  "/protected/": typeof ProtectedIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/protected/chat/$id": typeof ProtectedChatIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/demo"
    | "/imprint"
    | "/privacy"
    | "/protected"
    | "/share"
    | "/sitemap.xml"
    | "/terms"
    | "/auth/error"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/sign-up"
    | "/auth/sign-up-success"
    | "/auth/update-password"
    | "/collaborate/$chatId"
    | "/demo/$scenario"
    | "/protected/settings"
    | "/protected/usage"
    | "/share/$shareId"
    | "/demo/"
    | "/protected/"
    | "/api/auth/$"
    | "/protected/chat/$id";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/imprint"
    | "/privacy"
    | "/share"
    | "/sitemap.xml"
    | "/terms"
    | "/auth/error"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/sign-up"
    | "/auth/sign-up-success"
    | "/auth/update-password"
    | "/collaborate/$chatId"
    | "/demo/$scenario"
    | "/protected/settings"
    | "/protected/usage"
    | "/share/$shareId"
    | "/demo"
    | "/protected"
    | "/api/auth/$"
    | "/protected/chat/$id";
  id:
    | "__root__"
    | "/"
    | "/demo"
    | "/imprint"
    | "/privacy"
    | "/protected"
    | "/share"
    | "/sitemap.xml"
    | "/terms"
    | "/auth/error"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/sign-up"
    | "/auth/sign-up-success"
    | "/auth/update-password"
    | "/collaborate/$chatId"
    | "/demo/$scenario"
    | "/protected/settings"
    | "/protected/usage"
    | "/share/$shareId"
    | "/demo/"
    | "/protected/"
    | "/api/auth/$"
    | "/protected/chat/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DemoRoute: typeof DemoRouteWithChildren;
  ImprintRoute: typeof ImprintRoute;
  PrivacyRoute: typeof PrivacyRoute;
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  ShareRoute: typeof ShareRouteWithChildren;
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute;
  TermsRoute: typeof TermsRoute;
  AuthErrorRoute: typeof AuthErrorRoute;
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthSignUpRoute: typeof AuthSignUpRoute;
  AuthSignUpSuccessRoute: typeof AuthSignUpSuccessRoute;
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute;
  CollaborateChatIdRoute: typeof CollaborateChatIdRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo": {
      id: "/demo";
      path: "/demo";
      fullPath: "/demo";
      preLoaderRoute: typeof DemoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/imprint": {
      id: "/imprint";
      path: "/imprint";
      fullPath: "/imprint";
      preLoaderRoute: typeof ImprintRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/protected": {
      id: "/protected";
      path: "/protected";
      fullPath: "/protected";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/share": {
      id: "/share";
      path: "/share";
      fullPath: "/share";
      preLoaderRoute: typeof ShareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sitemap.xml": {
      id: "/sitemap.xml";
      path: "/sitemap.xml";
      fullPath: "/sitemap.xml";
      preLoaderRoute: typeof SitemapDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/error": {
      id: "/auth/error";
      path: "/auth/error";
      fullPath: "/auth/error";
      preLoaderRoute: typeof AuthErrorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/auth/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/sign-up": {
      id: "/auth/sign-up";
      path: "/auth/sign-up";
      fullPath: "/auth/sign-up";
      preLoaderRoute: typeof AuthSignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/sign-up-success": {
      id: "/auth/sign-up-success";
      path: "/auth/sign-up-success";
      fullPath: "/auth/sign-up-success";
      preLoaderRoute: typeof AuthSignUpSuccessRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/update-password": {
      id: "/auth/update-password";
      path: "/auth/update-password";
      fullPath: "/auth/update-password";
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/collaborate/$chatId": {
      id: "/collaborate/$chatId";
      path: "/collaborate/$chatId";
      fullPath: "/collaborate/$chatId";
      preLoaderRoute: typeof CollaborateChatIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/demo/": {
      id: "/demo/";
      path: "/";
      fullPath: "/demo/";
      preLoaderRoute: typeof DemoIndexRouteImport;
      parentRoute: typeof DemoRoute;
    };
    "/demo/$scenario": {
      id: "/demo/$scenario";
      path: "/$scenario";
      fullPath: "/demo/$scenario";
      preLoaderRoute: typeof DemoScenarioRouteImport;
      parentRoute: typeof DemoRoute;
    };
    "/protected/": {
      id: "/protected/";
      path: "/";
      fullPath: "/protected/";
      preLoaderRoute: typeof ProtectedIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/protected/settings": {
      id: "/protected/settings";
      path: "/settings";
      fullPath: "/protected/settings";
      preLoaderRoute: typeof ProtectedSettingsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/protected/usage": {
      id: "/protected/usage";
      path: "/usage";
      fullPath: "/protected/usage";
      preLoaderRoute: typeof ProtectedUsageRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/share/$shareId": {
      id: "/share/$shareId";
      path: "/$shareId";
      fullPath: "/share/$shareId";
      preLoaderRoute: typeof ShareShareIdRouteImport;
      parentRoute: typeof ShareRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/protected/chat/$id": {
      id: "/protected/chat/$id";
      path: "/chat/$id";
      fullPath: "/protected/chat/$id";
      preLoaderRoute: typeof ProtectedChatIdRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
  }
}

interface DemoRouteChildren {
  DemoScenarioRoute: typeof DemoScenarioRoute;
  DemoIndexRoute: typeof DemoIndexRoute;
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoScenarioRoute: DemoScenarioRoute,
  DemoIndexRoute: DemoIndexRoute,
};

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren);

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute;
  ProtectedUsageRoute: typeof ProtectedUsageRoute;
  ProtectedIndexRoute: typeof ProtectedIndexRoute;
  ProtectedChatIdRoute: typeof ProtectedChatIdRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedUsageRoute: ProtectedUsageRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedChatIdRoute: ProtectedChatIdRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(ProtectedRouteChildren);

interface ShareRouteChildren {
  ShareShareIdRoute: typeof ShareShareIdRoute;
}

const ShareRouteChildren: ShareRouteChildren = {
  ShareShareIdRoute: ShareShareIdRoute,
};

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ShareRoute: ShareRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSignUpSuccessRoute: AuthSignUpSuccessRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  CollaborateChatIdRoute: CollaborateChatIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
